export const BOOK_NAME_MAP = {
  Genesis: 'GEN',
  Exodus: 'EXO',
  Leviticus: 'LEV',
  Numbers: 'NUM',
  Deuteronomy: 'DEU',
  Joshua: 'JOS',
  Judges: 'JDG',
  Ruth: 'RUT',
  '1 Samuel': '1SA',
  '2 Samuel': '2SA',
  '1 Kings': '1KI',
  '2 Kings': '2KI',
  '2 Chronicles': '2CH',
  Isaiah: 'ISA',
  Ezekiel: 'EZK',
  Daniel: 'DAN',
  Proverbs: 'PRO',
  Joel: 'JOL',
  Amos: 'AMO',
  Jonah: 'JON',
  Micah: 'MIC',
  Habbakuk: 'HAB',
  Zephaniah: 'ZEP',
  Haggai: 'HAG',
  Zechariah: 'ZEC',
  Mark: 'MRK',
  Matthew: 'MAT',
  John: 'JHN',
  Acts: 'ACT',
  Romans: 'ROM',
  '1 Corinthians': '1CO',
  '1 Thessalonians': '1TH',
  '2 Thessalonians': '2TH',
  Philippians: 'PHP',
  Colossians: 'COL',
  Hebrews: 'HEB',
  James: 'JAS',
  Jude: 'JUD',
  Revelation: 'REV',
  Psalm: 'PSA',
};

// Only including those books who have a plan day where the whole book is read
export const CHAPTERS = {
  Ruth: 4,
  Joel: 3,
  Amos: 9,
  Jonah: 4,
  Micah: 7,
  Habbakuk: 3,
  Zephaniah: 3,
  Haggai: 2,
  Zechariah: 14,
  '1 Thessalonians': 5,
  '2 Thessalonians': 3,
  Philippians: 4,
  Colossians: 4,
  Hebrews: 13,
  James: 5,
  Jude: 1,
};
