import { Complete } from './Home/types';

const Badge = (
  title: string,
  description: string,
  src: string,
  condition: (completions: Complete[]) => boolean,
  hidden: boolean = false,
  psalms: boolean = false,
) => ({
  title,
  description,
  image: src,
  condition,
  hidden,
  psalms,
});

const badges = [
  Badge(
    'In the Beginning',
    `You read the whole book of Genesis`,
    '/badges/genesis.png',
    () => false,
  ),
  Badge(
    'An Outstretched Arm',
    'You read the whole book of Exodus',
    '/badges/exodus.png',
    () => false,
  ),
  Badge(
    'A Priestly Ephod',
    'You read the priestly code in the book of Leviticus',
    '/badges/leviticus.png',
    () => false,
  ),
  Badge(
    'A Second Time',
    'You read the whole book of Deuteronomy',
    '/badges/deuteronomy.png',
    () => false,
  ),
  Badge(
    'Son of Nun',
    'You completed all the readings from the book of Joshua',
    '/badges/joshua.png',
    () => false,
  ),
  Badge(
    'Cried Out to YHWH',
    'You read the whole book of Judges',
    '/badges/judges.png',
    () => false,
  ),
  Badge(
    `Where You Go, I'll Go`,
    'You read the whole book of Ruth',
    '/badges/ruth.png',
    () => false,
  ),
  Badge(
    'The End of a Dynasty',
    'You read the whole book of 1 Samuel',
    '/badges/1samuel.png',
    () => false,
  ),
  Badge(
    'The Beginning of a Dynasty',
    'You read the whole book of 2 Samuel',
    '/badges/2samuel.png',
    () => false,
  ),
  Badge(
    'The Fall of Kings',
    'You read the whole book of 1 Kings',
    '/badges/1kings.png',
    () => false,
  ),
  Badge(
    'Away from Her Land',
    'You read the whole book of 2 Kings',
    '/badges/2kings.png',
    () => false,
  ),
  Badge(
    'My Holy Mountain',
    `You read about God's holy mountain in Isaiah 11`,
    '/badges/holy-mountain.png',
    () => false,
    true,
  ),
  Badge(
    'The Prophet Isaiah',
    'You completed all the readings from proto-Isaiah',
    '/badges/proto-isaiah.png',
    () => false,
  ),
  Badge(
    'The Suffering Servant',
    'You completed all the readings from deutero (and trito) Isaiah',
    '/badges/deutero-isaiah.png',
    () => false,
  ),
  Badge(
    'The Unfaithful Wife',
    'You read the grim description of unfaithful Israel',
    '/badges/unfaithful-wife.png',
    () => false,
    true,
  ),
  Badge(
    'The New Jerusalem',
    'You completed all the readings from the book of Ezekiel',
    '/badges/ezekiel.png',
    () => false,
  ),
  Badge(
    'The Years the Locust have Taken',
    'You read all of the books of Joel and Amos',
    '/badges/joel-amos.png',
    () => false,
  ),
  Badge(
    'A Universal Hope',
    'You read all of the books of Jonah and Micah',
    '/badges/jonah-micah.png',
    () => false,
  ),
  Badge(
    'Justice and Mercy',
    'You read all of the books of Habbakuk, Zephaniah, and Haggai',
    '/badges/hab-zeph-hag.png',
    () => false,
  ),
  Badge(
    'Latter',
    'You completed all the readings from the Latter Prophets',
    '/badges/latter.png',
    () => false,
  ),
  Badge('The Son of Man', 'You read the whole book of Mark', '/badges/mark.png', () => false),
  Badge('A New Moses', 'You read the whole book of Matthew', '/badges/matthew.png', () => false),
  Badge('A Torah Psalm', 'You read Psalm 119', '/badges/119.png', () => false, false, true),
  Badge(
    'The Word Became Flesh',
    'You read the whole book of John',
    '/badges/john.png',
    () => false,
  ),
  Badge(
    'Seated at the Right Hand',
    'You read about the first martyr and his vindication in Christ',
    '/badges/acts.png',
    () => false,
    true,
  ),
  Badge(
    'The Family of God',
    'You read the whole book of Romans',
    '/badges/romans.png',
    () => false,
  ),
  Badge(
    'The Resurrection of the Body',
    'You read one of the most glorious pieces of prose in the epistles: 1 Corinthians 15',
    '/badges/resurrection.png',
    () => false,
    true,
  ),
  Badge(
    'Pauline',
    'You completed all the readings from the Pauline epistles',
    '/badges/pauline.png',
    () => false,
  ),
  Badge(
    'A Great High Priest',
    'You read the whole book of Hebrews',
    '/badges/hebrews.png',
    () => false,
  ),
  Badge(
    'Brothers of Jesus',
    'You read all of the books of James and Jude',
    '/badges/james-jude.png',
    () => false,
  ),
  Badge('The End', 'You read the whole book of Revelation', '/badges/revelation.png', () => false),
];

export default badges;
